### PR TITLE
Migration to Paket

### PR DESCRIPTION
**Pull request by sergey-tihon**
New things:
* Migration to Paket
* Latest version of ProvidedTypes.fs
* Reference API

Almost everything is done.
@forki Could you help me with Nuget packaging using Paket template file?
I can't understand how to specify files that I want to add

### CODE REVIEW

**Comment by forki** [comment]
docs can be found at: http://fsprojects.github.io/Paket/template-files.html#Files

But you don't have to specify the files if you do it like https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/paket.template

**Comment by sergey-tihon** [comment]
I used template generate by ProjectScaffold
https://github.com/sergey-tihon/DynamicsCRMProvider/blob/master/src/DynamicsCRMProvider/paket.template

My `bin` folder:
image
Generated `nupkg`
image

Why not all files are added?

**Comment by forki** [comment]
yes if you want to add more files than the project itself then you need to do with `type file` like
https://github.com/fsprojects/Paket/blob/master/nuget/paket.template#L21

/cc @mavnn

**Comment by sergey-tihon** [comment]
Thank, but it is not obvious
Strange that I need to specify everything except one file, and if I specify mail dll - it fails

**Comment by forki** [comment]
Please add a Paket issue where we can discuss how to improve things

**Comment by sergey-tihon** [comment]
What do you think, can we merge this PR?
I think that it does not add more illegal things.

**Comment by forki** [comment]
good point ;-)

**Pull request merged**
