### PR TITLE
Migration to Microsoft.CrmSdk.* assemblies

### PR DESCRIPTION
**Pull request by sergey-tihon**
Added dependency to official CRM package - Microsoft.CrmSdk.CoreAssemblies

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@pezipink You used only [deviceidmanager.cs](https://github.com/sergey-tihon/DynamicsCRMProvider/blob/master/src/Microsoft.Crm.Services.Utility/deviceidmanager.cs)

The only thing I need right now is good example of assembly binding redirection for TP)

**Comment by pezipink** [comment]
ahh right, once again if memory serves we well I had to bring that in to support CRM Online for some reason...

**Comment by sergey-tihon** [comment]
I need an advice and good example of assembly binding redirection.
I have tried to reuse implementation from `RProvider` but it does not work on my machine. `AssemblyResolve` event is not fired.
Should I create design time assembly? Is it important step?
// @pezipink @mavnn @tpetricek

**Comment by pezipink** [comment]
What is the exact scenario here?  AssemblyResolve only fires if it cannot resolve the assembly for some reason.  I have used it before in type providers including in the IP here

https://github.com/pezipink/InteractiveProvider/blob/master/InteractiveProvider/InteractiveProvider.fs#L13

I am not 100% what you are trying to do though?

**Pull request merged**
